### ISSUE TITLE
アイコンの作成

### ISSUE THREAD

**Issue by km-tr** [webpack-japan/webpack.js.org#23]
[参考(webpack-africa)](https://dev.to/thelarkinn/i-maintain-webpack-ask-me-anything-an8)

**Comment by hivesbee** [comment]
つくった  
PR どうしますか？
![webpack-japan-icon](https://user-images.githubusercontent.com/6626178/47102856-c3577f80-d278-11e8-866f-3b1dbd1addc3.png)

**Comment by km-tr** [comment]
完成したらアイコンを入れておきます。

**Comment by hivesbee** [comment]
修正しました  
![webpack-japan-icon-3](https://user-images.githubusercontent.com/6626178/47161736-9913c980-d32d-11e8-9048-eed9154dee6a.png)

**Comment by km-tr** [comment]
良いと思います。

**Comment by hivesbee** [comment]
影が出る問題ですが、画像が正方形バージョンを用意してみました。  
もしかして引き伸ばされて影がでてしまったのかな、と 🤔 
![webpack-japan-icon-4](https://user-images.githubusercontent.com/6626178/47164442-05dd9280-d333-11e8-84d7-6b877fa40bc0.png)
